package com.t2tierp.suporte.cliente;

import com.t2tierp.suporte.java.ArquivoVO;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import org.openswing.swing.client.GridControl;
import org.openswing.swing.mdi.client.InternalFrame;

/**
 * <p>Title: T2Ti ERP</p>
 * <p>Description: Tela ChamadoDetalhe.</p>
 *
 * <p>The MIT License</p>
 *
 * <p>Copyright: Copyright (C) 2010 T2Ti.COM
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 *        The author may be contacted at:
 *            t2ti.com@gmail.com</p>
 *
 * @author Claudio de Barros (t2ti.com@gmail.com)
 * @version 1.0
 */
public class ChamadoDetalhe extends InternalFrame {

    private ChatGridController chatController;
    private ArquivoGridController arquivoController;

    public ChamadoDetalhe(ChamadoDetalheController chamadoDetalheController) {
        initComponents();

        chatController = new ChatGridController(this);
        gridMensagem.setController(chatController);
        gridMensagem.setGridDataLocator(chatController);
        chatController.setChamado(chamadoDetalheController.getChamado());

        arquivoController = new ArquivoGridController();
        gridArquivo.setController(arquivoController);
        gridArquivo.setGridDataLocator(arquivoController);
        arquivoController.setChamado(chamadoDetalheController.getChamado());
    }

    private void enviaMensagem() {
        if (!txtMensagem.getText().trim().equals("")) {
            try {
                chatController.enviaMensagem("Suporte: " + txtMensagem.getText());
                txtMensagem.setText("");
                txtMensagem.requestFocus();
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao enviar a mensagem!\n" + ex.getMessage(), "Erro do Sistema", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void consultaArquivos() {
        gridArquivo.reloadData();
    }

    private void abreArquivo() {
        if (gridArquivo.getSelectedRow() != -1) {
            ArquivoVO arquivo = (ArquivoVO) gridArquivo.getVOListTableModel().getObjectForRow(gridArquivo.getSelectedRow());
            try {
                arquivoController.abreArquivo(arquivo);
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao abrir o arquivo!", "Erro do Sistema", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um arquivo!", "Informação do Sistema", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public GridControl getGridMensagem() {
        return gridMensagem;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMensagem = new javax.swing.JTextField();
        btnConsultaArquivo = new javax.swing.JButton();
        btnEnviaMensagem = new javax.swing.JButton();
        btnAbrirArquivo = new javax.swing.JButton();
        gridMensagem = new org.openswing.swing.client.GridControl();
        dateColumn4 = new org.openswing.swing.table.columns.client.DateColumn();
        textColumn5 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn3 = new org.openswing.swing.table.columns.client.TextColumn();
        jPanel2 = new javax.swing.JPanel();
        gridArquivo = new org.openswing.swing.client.GridControl();
        dateColumn5 = new org.openswing.swing.table.columns.client.DateColumn();
        textColumn6 = new org.openswing.swing.table.columns.client.TextColumn();

        setTitle("T2Ti ERP - Suporte Tecnico");
        setPreferredSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11));
        jLabel1.setText("Mensagem:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel1, gridBagConstraints);

        txtMensagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMensagemKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(txtMensagem, gridBagConstraints);

        btnConsultaArquivo.setText("Consultar Arquivos");
        btnConsultaArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaArquivoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnConsultaArquivo, gridBagConstraints);

        btnEnviaMensagem.setText("Enviar Mensagem");
        btnEnviaMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviaMensagemActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnEnviaMensagem, gridBagConstraints);

        btnAbrirArquivo.setText("Abrir Arquivo");
        btnAbrirArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirArquivoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnAbrirArquivo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        gridMensagem.setAutoLoadData(false);
        gridMensagem.setFunctionId("chat");
        gridMensagem.setValueObjectClassName("com.t2tierp.suporte.java.ChatVO");
        gridMensagem.setVisibleStatusPanel(false);
        gridMensagem.getColumnContainer().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        dateColumn4.setColumnName("dataMensagem");
        dateColumn4.setHeaderColumnName("Data Mensagem");
        dateColumn4.setHeaderFont(new java.awt.Font("Arial", 1, 11));
        gridMensagem.getColumnContainer().add(dateColumn4);

        textColumn5.setColumnName("horaMensagem");
        textColumn5.setHeaderColumnName("Hora Mensagem");
        textColumn5.setHeaderFont(new java.awt.Font("Arial", 1, 11));
        gridMensagem.getColumnContainer().add(textColumn5);

        textColumn3.setColumnName("mensagem");
        textColumn3.setHeaderColumnName("Mensagem");
        textColumn3.setHeaderFont(new java.awt.Font("Arial", 1, 11));
        textColumn3.setPreferredWidth(700);
        gridMensagem.getColumnContainer().add(textColumn3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(gridMensagem, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Arquivos Enviados"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        gridArquivo.setAutoLoadData(false);
        gridArquivo.setFunctionId("arquivo");
        gridArquivo.setValueObjectClassName("com.t2tierp.suporte.java.ArquivoVO");
        gridArquivo.getColumnContainer().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        dateColumn5.setColumnName("dataEnvio");
        dateColumn5.setHeaderColumnName("Data Envio");
        dateColumn5.setHeaderFont(new java.awt.Font("Arial", 1, 11));
        gridArquivo.getColumnContainer().add(dateColumn5);

        textColumn6.setColumnName("horaEnvio");
        textColumn6.setHeaderColumnName("Hora Envio");
        textColumn6.setHeaderFont(new java.awt.Font("Arial", 1, 11));
        gridArquivo.getColumnContainer().add(textColumn6);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(gridArquivo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMensagemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMensagemKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            enviaMensagem();
        }
    }//GEN-LAST:event_txtMensagemKeyPressed

    private void btnEnviaMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviaMensagemActionPerformed
        enviaMensagem();
    }//GEN-LAST:event_btnEnviaMensagemActionPerformed

    private void btnConsultaArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaArquivoActionPerformed
        consultaArquivos();
    }//GEN-LAST:event_btnConsultaArquivoActionPerformed

    private void btnAbrirArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirArquivoActionPerformed
        abreArquivo();
    }//GEN-LAST:event_btnAbrirArquivoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirArquivo;
    private javax.swing.JButton btnConsultaArquivo;
    private javax.swing.JButton btnEnviaMensagem;
    private org.openswing.swing.table.columns.client.DateColumn dateColumn4;
    private org.openswing.swing.table.columns.client.DateColumn dateColumn5;
    private org.openswing.swing.client.GridControl gridArquivo;
    private org.openswing.swing.client.GridControl gridMensagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.openswing.swing.table.columns.client.TextColumn textColumn3;
    private org.openswing.swing.table.columns.client.TextColumn textColumn5;
    private org.openswing.swing.table.columns.client.TextColumn textColumn6;
    private javax.swing.JTextField txtMensagem;
    // End of variables declaration//GEN-END:variables
}
